export const GAME_CONFIG = {
  ENEMY_SPEED: 2,
  MIN_DISTANCE: 50,
  ATTACK_RANGE: 60,
  ATTACK_DAMAGE: 10,
  PLAYER_SPEED: 10,
  INITIAL_HEALTH: 100,
  ATTACK_INTERVAL: 1000,
  ATTACK_COOLDOWN: 1000,
};
